version: "3.7"


services:

  item-app:
    container_name: item-app
    image: cahyogusti/item-app:v1
    ports:
        - "80:8080"
    depends_on:
        - item-db
    
   
    

  item-db:

    container_name: item-db
    image: mongo:3
    ports: 
        - "27017:27017"
    volumes:
        - "app-db:/data/db"


volumes:

  app-db:
      name: app-db
