apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs
  labels:
    name: karsajobs
spec:
  replicas: 2
  selector:
    matchLabels:
      name: karsajobs
  template:
    metadata:
      name: karsajobs
      labels:
        name: karsajobs
    spec:
      containers:
        - name: karsajobs
          image: cahyogusti/karsajobs:latest
          ports:
           - containerPort: 8080
          env:
          - name: APP_PORT
            value: "8080"
          - name: MONGO_HOST
            value: mongodb
          - name: MONGO_USER
            valueFrom:
              secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_ROOT_USERNAME
          - name: MONGO_PASS
            valueFrom:
              secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_ROOT_PASSWORD
